var JOKES = [
    "FlukeDude Ltd. cannot sue me because they do not have trademarks nor copyrights over this game.",
    "Pls give us full marks. Mrs Jeseil.",
    "Pls give us full marks. Mrs Jeseil.",
    "Pls give us full marks. Mrs Jeseil.",
    "Pls give us full marks. Mrs Jeseil.",
    "Pls give us full marks. Mrs Jeseil.",
    "Pls give us full marks. Mrs Jeseil.",
    "Pls give us full marks. Mrs Jeseil.",
    "Pls give us full marks. Mrs Jeseil.",
    "Pls give us full marks. Mrs Jeseil.",
    "Pls give us full marks. Mrs Jeseil.",
    "Pls give us full marks. Mrs Jeseil.",
    "Pls give us full marks. Mrs Jeseil.",
    "Pls give us full marks. Mrs Jeseil.",
    "Pls give us full marks. Mrs Jeseil.",
    "Pls give us full marks. Mrs Jeseil.",
    "Pls give us full marks. Mrs Jeseil.",
    "Pls give us full marks. Mrs Jeseil.",
    "Always Free!",
    "Try out The Impossible Game 2 +",
    "Try out The Impossible Game 2 +",
    "Try out The Impossible Game 2 +",
    "Try out The Impossible Game 2 +",
    "Try out The Impossible Game 2 +",
    "Try out The Impossible Game 2 +",
    "Try out The Impossible Game 2 +",
    "Try out The Impossible Game 2 +",
    "Try out The Impossible Game 2 +",
    "Fun Fact: I work on this until 3am",
    "Fun Fact: I work on this until 3am",
    "Fun Fact: I work on this until 3am",
    "Fun Fact: I work on this until 3am",
    "Fun Fact: I work on this until 3am",
    "Fun Fact: I work on this until 3am",
    "This is actually based on the android app",
    "This is actually based on the android app",
    "This is actually based on the android app",
    "This is actually based on the android app",
    "This is actually based on the android app",
    "This is actually based on the android app",
    "Shout out to d016 for allowing me to make this project possible!",
    "Shout out to d016 for allowing me to make this project possible!",
    "Shout out to d016 for allowing me to make this project possible!",
    "Shout out to d016 for allowing me to make this project possible!",
    "Shout out to d016 for allowing me to make this project possible!",
    "Shout out to d016 for allowing me to make this project possible!",
    "Shout out to d016 for allowing me to make this project possible!",
    "Shout out to d016 for allowing me to make this project possible!",
  ],
  currentJoke = JOKES[Math.floor(Math.random() * JOKES.length)];
